import type {
  PatchProposalRequest,
  PatchProposalResponse,
  PlanRequest,
  PlanResponse,
} from "@/lib/ai/contracts"
import { allowedVerificationCommands } from "@/lib/verification/commands"

export function createPlan(request: PlanRequest): PlanResponse {
  const dirtyFileText =
    request.dirtyFiles.length > 0
      ? request.dirtyFiles.join(", ")
      : "no currently dirty files"

  return {
    summary: `Plan for ${request.activeFile}: ${request.intent}`,
    contextFiles: [request.activeFile, ...request.dirtyFiles].filter(
      (path, index, paths) => paths.indexOf(path) === index
    ),
    steps: [
      {
        id: "read-context",
        title: "Read relevant context",
        detail: `Inspect ${request.activeFile} plus ${dirtyFileText} before producing changes.`,
        risk: "low",
      },
      {
        id: "draft-small-patch",
        title: "Draft a small patch",
        detail:
          "Keep the patch narrow, explain every changed file, and avoid unrelated formatting churn.",
        risk: "medium",
      },
      {
        id: "verify",
        title: "Verify before commit",
        detail: `Run ${allowedVerificationCommands.join(", ")} and attach results to the assistant summary.`,
        risk: "low",
      },
    ],
    verification: allowedVerificationCommands,
  }
}

export function createPatchProposal(
  request: PatchProposalRequest
): PatchProposalResponse {
  return {
    proposals: [
      {
        id: "patch-active-file",
        filePath: request.activeFile,
        title: "Apply scoped edits to active file",
        diffPreview:
          "--- before\n+++ after\n@@\n-// AI patch placeholder\n+// Patch will be generated by the approved local agent",
        requiresApproval: true,
      },
    ],
    safetyNote:
      "This endpoint only proposes patch metadata. File writes must be performed by the local workspace agent after user approval.",
  }
}
